apiVersion: v1
kind: Pod
metadata:
  name: moodle
  labels:
    name: moodle
spec:
  containers:
    - image: romero/moodleapp_apache-php
      name: moodle
      ports:
        - containerPort: 80
          name: moodle
      volumeMounts:
          # Name must match the volume name below.
        - name: my-data
          # Mount path within the container.
          mountPath: /var/www/moodle
          # Name must match the volume name below.
        - name: my-data
          # Mount path within the container.
          mountPath: /var/www/moodle
  volumes:
    - name: my-data
      gcePersistentDisk:
        # This GCE persistent disk must already exist.
        pdName: moodle-disk
        fsType: ext4
