apiVersion: v1
kind: ReplicationController
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    app: moodle
  template:
    metadata:
      name: moodle
      labels: 
        app: moodle
    spec:
      containers:
        - name: moodle
          image: romero/moodleapp-apache-php
          env:
            - name: MOODLE_DB_PASSWORD
              # Change this - must match mysql.yaml password.
              value: rom-admin
          ports:
            - containerPort: 80
              name: moodle
          volumeMounts:
              # Name must match the volume name below.
            - name: moodle-data
              # Mount path within the container.
              mountPath: /var/www/moodledata
      nodeName: gke-moodle-cluster-default-pool-7ea7bac9-ruxu
      volumes:
        - name: moodle-data
          gcePersistentDisk:
            # This GCE persistent disk must already exist.
            pdName: moodle-disk
            fsType: ext4