apiVersion: v1
kind: Service
metadata:
  labels:
    name: moodle
  name: moodle
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: moodle
