apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - resources:
        limits:
          cpu: 0.5
      image: romero/moodleapp_mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          # Change this password!
          value: rom-admin
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # This name must match the volumes.name below.
        - name: my-data
          mountPath: /var/lib/mysql
  volumes:
    - name: my-data
      gcePersistentDisk:
        # This disk must already exist.
        pdName: mysql-disk
        fsType: ext4
